### ISSUE TITLE
Has No Network

### ISSUE THREAD

**Issue by pgimeno** [minetest-mods/technic#404]
Very often, but mostly at random, when placing devices in a power line that has a working switching station, I get `<device> Has No Network` and it doesn't work. In other occasions they connect to the wrong devices, for example stacking hydro generators without connecting them often makes one or more of them work with a switching station above them.

Removing either the device, the switching station or the cable and placing them again does not fix it. It typically requires a server restart.

Reverting d3f40e0 (introduced in pr #315) makes everything work as expected.

**Comment by numberZero** [comment]
Er, this should have been fixed in 088eea1e3ba42fd13510861025e1c9fc989799a0, although might be broken again by c4acb7225a059b9eb40c1149ba043a55016eab16.

**Comment by pgimeno** [comment]
I've checked out 088eea1 and it doesn't fix the issue.

I've also managed to create a reliable reproduction recipe. It seems that order matters.

1. Place dirt on the ground.
2. Place a switching station on it.
3. Remove the dirt.
4. Place a LV cable where the dirt was (under the switching station).
5. Place a LV cable next to that one.
6. Place a LV solar cell on the last cable.
7. Observe now that the solar cell Has No Network.

However, when placing the cable first, then the switching station and the solar cell, everything works as expected, and it tends to be more stable.

**Comment by numberZero** [comment]
@pgimeno Thank you very much for the recipe, it will help investigating the issue.

**Comment by numberZero** [comment]
86fb981b fixed the network traversal bug that have been causing problems in the sequence @pgimeno described. Make sure you have that version at least.

**Comment by pgimeno** [comment]
Sorry about that. In my defense, this report predates that commit, and I didn't update before retesting for fear of requiring a too modern server (has happened with other mods).

I haven't tried too hard to reproduce the problems in the OP, I'm not minetesting much these days, all I can say is that after some simple experiments in local, everything seemed to work as expected. I haven't updated the server where the issue originally showed up yet, though (it's in a LAN).

Maybe meanwhile @beyondlimits can shed more light about whether it's still reproducible with current master.

**Comment by beyondlimits** [comment]
Too bad it's still happening. Connect solar power generators to the switching station, but instead of immediately connecting the first placed panel, do it in reverse, so that the last generator is the one that connects the whole array. Power station will yield wrong values and probably all the generators except the one nearest the power station will claim they have no network.

It's also get messed up when connecting solar power generators in 2x2 array.

**Comment by numberZero** [comment]
@beyondlimits can you post a screenshot of such system?

**Comment by beyondlimits** [comment]
![screenshot_20180629_213536](https://user-images.githubusercontent.com/7702857/42111343-6ab88b16-7be4-11e8-90d0-cf4869f67873.png)

You may also watch video of the mess in action: http://a140118.drivehq.com/minetest180629.mp4

**Comment by numberZero** [comment]
Generators aren’t conductive, are they?

В Fri, 29 Jun 2018 12:39:27 -0700
beyondlimits <notifications@github.com> пишет:

> ![screenshot_20180629_213536](https://user-images.githubusercontent.com/7702857/42111343-6ab88b16-7be4-11e8-90d0-cf4869f67873.png)
> 
> You may also watch video of the mess in action:
> http://a140118.drivehq.com/minetest180629.mp4
>

**Comment by pgimeno** [comment]
It's a bit messy. I think there are several bugs at play here.

1. When you have a generator connected to a network, placing another generator immediately next to it connects to it. When restarting the server, the second generator loses power.
2. The same generator can have different networks due to its connectivity and the fact that it's not conductive. This leads to the paradox that it can multiply its power, one instance per connected network, and to unexpected side effects.
3. Solar power generators in particular connect to adjacent cables in any position and not just below them, yet the cables don't visually reach them.


To illustrate them, I'll use side view ASCII diagrams, with `S` meaning switching station, `C` cable, `H` hydro generator and `L` light (solar power) generator:

```
S
CL
```

In this situation, the generator is powered (bug 3), AND placing another generator to the right of the `L` makes it connected (bug 1). Same happens in this situation (another instance of bug 3):

```
S
C
L
```

However, when restarting, the second generator loses power (bug 1 side effect). When adding the cable last, the result is the same as with a server restart.

In this situation (bug 2):

```
S S
CHC
```

the hydro generator is feeding two networks at the same time, effectively doubling its power.

In this other situation (bug 2):

```
S
CLL
 CC
```

the rightmost generator lacks a network, even though it's connected to the first and the first does have a network.

**Comment by numberZero** [comment]
Yes, there are several well-known bugs. The root is the very essence of network handling in `technic`, it relies on the switching station but caches the network, and does both things improperly.

> 3. Solar power generators in particular connect to adjacent cables in any position and not just below them, even though the cables don't visually reach them.

Network scanning is still direction-independent. Even supply converters, while respecting direction when determining conversion type, happily connect to each compatible network around. #296

> 2. The same generator can have different networks due to its connectivity and the fact that it's not conductive. This leads to the paradox that it can multiply its power, one instance per connected network, and to unexpected side effects.

That’s called “overclocking.” That’s unfair for infinite generators (like solar panels) and supply converters (because the change is asymmetric there), but fine for other machines like fuel-fired generators (that increase fuel consumption accordingly). #277 #313

> 1. When you have a generator connected to a network, placing another generator immediately next to it connects to it. When restarting the server, the second generator loses power.

Something new. Yet another bug in the new dead-end handling, I suppose.

Really, the current code is inherently crapped. It might be well-designed (for running several small networks) once a long time ago, but all the additions and fixes and optimizations made it hardly maintainable. See #380 for a spark of hope; not sure of the state that project is currently in, though.

**Comment by pgimeno** [comment]
Thanks for the pointers. After more detailed experiments, I believe the problems I had in the OP were caused by a mix of factors including the issues reported so far, especially by issues that were fixed by 86fb981. Since the other issues have their own number or have been fixed already, the remaining problem is (1), and if desired, I can close this issue and open a new one for that, or we can keep this issue open just for that bug.

**Comment by pgimeno** [comment]
@beyondlimits: Hopefully @numberZero can confirm this, but I believe this is how you're supposed to connect solar panels, not just by placing them next to each other (which shouldn't work, and that's the bug under discussion):

![solar panel connection](https://user-images.githubusercontent.com/4267396/42133639-a966e67e-7d2d-11e8-8c79-7b54ac05e878.png)
